# Generated by Django 4.2.5 on 2023-09-06 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charityManager', '0002_rename_ngo_id_ngotype_ngo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('desc', models.CharField(max_length=512)),
            ],
        ),
        migrations.RemoveField(
            model_name='ngomaster',
            name='ngo_email',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='user_password',
        ),
        migrations.AddField(
            model_name='ngomaster',
            name='ngo_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ngomaster',
            name='ngo_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngotype',
            name='ngo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityManager.charitytype'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='user_pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charityManager.charitytype'),
        ),
    ]
